### PR TITLE
Update .gitignore file

### PR DESCRIPTION
**Pull request by singhaditya28**
Summary:
Updated .gitignore file for stability and security.

Test Plan:
Checked that all the files mentioned are not read

### CODE REVIEW

**Comment by cooperlees** [comment]
Hi, thanks for the PR. How have you generated this list of “stability and security” enhancements here for the ignore file? I generally just add as things come up that I don’t want in the repo ...

I haven’t looked into why CI failed here, but if you get that to pass I’ll merge.

**Comment by singhaditya28** [comment]
There is some problem with setup.py, ptr.py, ci.py and subprocess.py due to which error is being raised not because there is any problem in my updation. You can check the log as well as my file to confirm that.Thus, you can force merge the commits. 👍 😃 

Thanks in Advance.

**Comment by cooperlees** [comment]
Ahh - new upstream typeshed has changed returncode to be an optional int - PR incoming.

**Comment by cooperlees** [comment]
Can you please explain your claim for stability and security that this PR addresses please. I'm just interested, cause I'll be honest, it does not make sense.

All this achieves is to just ignore files to no add to the repo ...

**Comment by cooperlees** [comment]
> There is some problem with setup.py, ptr.py, ci.py and subprocess.py due to which error is being raised not because there is any problem in my updation. You can check the log as well as my file to confirm that.Thus, you can force merge the commits. 👍 😃
> 
> Thanks in Advance.

Typing Error fixed here:
https://github.com/facebookincubator/ptr/pull/96

**Comment by singhaditya28** [comment]
> > There is some problem with setup.py, ptr.py, ci.py and subprocess.py due to which error is being raised not because there is any problem in my updation. You can check the log as well as my file to confirm that.Thus, you can force merge the commits. 👍 😃
> > Thanks in Advance.
> 
> Typing Error fixed here:
> #96

ThankYou for fixing this 👍 😄

**Comment by singhaditya28** [comment]
> Can you please explain your claim for stability and security that this PR addresses please. I'm just interested, cause I'll be honest, it does not make sense.
> 
> All this achieves is to just ignore files to no add to the repo ...

Sure, This ignores all the files which are wastage and many people take it casually **but**, It also filters out some secret files which can accidently be thrown in front of the user like cache files which can leak out some vital information.
Hope I am able to  make you understand 👍 😃

**Comment by singhaditya28** [comment]
Please merge this PR.

**Comment by cooperlees** [comment]
Thanks for the effort but I don’t agree with some of the entries and project does not need this. All the best.

**Comment by singhaditya28** [comment]
So you can always suggest some edits. Please! 👍 😃 .But merging this will help

**Pull request closed without merging**
